name: preffecture
description: "A modern Prefecture Management App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  velocity_x: ^4.2.0
  carousel_slider: ^5.1.2  # <--- Ensure this line is here
  add_2_calendar: ^3.0.1
  url_launcher: ^6.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1 # For geographic coordinates
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4  # Downgraded slightly to match notifications v17
  font_awesome_flutter: ^10.12.0
  barcode_widget: ^2.0.4
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  google_sign_in: ^7.2.0
  google_sign_in_ios: ^6.3.0
  google_sign_in_platform_interface: ^3.1.0
  country_picker: ^2.0.27
  phone_numbers_parser: ^9.0.20



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/4727_Logo_copy.png
    - assets/images/logo-eq.svg
    - assets/images/kampachi-logo.png
    - assets/images/4727_with_border_Logo.png
    - assets/images/japan_map.png
    - assets/sponsors/logo.svg
    - assets/images/casio-logo.png
    - assets/images/g-shock.png
    - assets/images/mitsubishi-logo.webp
    - assets/images/uniqlo-logo.png
    - assets/images/toho-logo.png
    - assets/images/japan-airline.png
    - assets/images/suntory-logo.png
    - assets/images/shisheido-logo.png
    - assets/food/12.jpg
    - assets/food/14.jpg
    - assets/food/15.jpeg
    - assets/images/sunburst.png
    - assets/images/ippudo.avif
    - assets/images/MAiSEN-Logo.avif
    - assets/images/ippudo_black.png
    - assets/images/kampachi_white.png
    - assets/images/4727_Logo_V2.png
    - assets/images/logo-eq.png
    - assets/images/sky51.jpg
    - assets/images/kampachi-1.jpeg    
    - assets/images/kampachi-2.jpeg
    - assets/images/IPPUDO.jpg
    - assets/images/MAiSEN.jpg